version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  mongo:
    image: mongo:4.4.3-bionic
    ports:
      - "27017:27017"
    volumes:
      - pg_project:/data/db
